source 'https://rubygems.org'

gem 'sinatra', '1.4.7'
gem 'rack', '1.5.2'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'

gem 'sinatra-contrib'

gem 'bluecloth'

group :test do
  gem 'rack-test'
end